service: nft-sales-listener
runtime: nodejs
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.75
resources:
  cpu: 1
  memory_gb: 10
  disk_size_gb: 2
readiness_check:
  app_start_timeout_sec: 1800